### ISSUE TITLE
Training code 

### ISSUE THREAD

**Issue by jiandandan001** [hyk1996/Degradation-Invariant-ReID-pytorch#1]
Thank you for this great work. 

Could you please share the training code? Thanks.

**Comment by Yukun-Huang** [comment]
Thank you for your attention, I will release the training code next month (around April 10th) and let you know then.

**Comment by jiandandan001** [comment]
> Thank you for your attention, I will release the training code next month (around April 10th) and let you know then.

Thanks.

**Comment by wsysuan** [comment]
Hi, can you publish the training code now?

**Comment by Yukun-Huang** [comment]
Hi guys, the training code is released.
