### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by ForeUP** [hyk1996/Degradation-Invariant-ReID-pytorch#2]
It's a great job and helps me a lot with my study.
Could you share the datasets if it's convenient?
Because of the randomness involved, although the article described very specific, but can not guarantee the effect of reproduction, and it is not convenient for follow-up researchs comparison, thank you again!

**Comment by Yukun-Huang** [comment]
Hi, I'm sorry that I don't have the rights to distribute these datasets. To construct the cross-resolution MLR-CUHK03, MLR-VIPeR, and CAVIAR benchmarks, you may follow the AAAI 2018 paper ["Deep Low-Resolution Person Re-Identification"](https://ojs.aaai.org/index.php/AAAI/article/view/12284) and use the split protocol files provided in data_splits/ from [Google Drive](https://drive.google.com/drive/folders/1anHkFyEJaQWRsbkmVFjZX9y71zzb7rCs?usp=sharing).
