### ISSUE TITLE
Person ID Split

### ISSUE THREAD

**Issue by ForeUP** [hyk1996/Degradation-Invariant-ReID-pytorch#3]
Hello, the result I tested using your model is as high as 99.7 rank-1. As can be seen from the example of your dataset, the Person ID we selected is different. Could you please share the partition list or  the whole dataset？
```shell
eval mode:  single_shot
Evaluation with f_fuse:
Rank@1=99.7  Rank@5=100.0  Rank@10=100.0  Rank@20=100.0  mAP=99.8
Evaluation with f_inv:
Rank@1=99.6  Rank@5=100.0  Rank@10=100.0  Rank@20=100.0  mAP=99.7
Evaluation with f_sen:
Rank@1=99.5  Rank@5=100.0  Rank@10=100.0  Rank@20=100.0  mAP=99.7
```
 Thank you very much!

**Comment by ForeUP** [comment]
I used the responsibility to split the IDs:
[@inproceedings{xiao2016learning,
  title={Learning Deep Feature Representations with Domain Guided Dropout for Person Re-identification},
  author={Xiao, Tong and Li, Hongsheng and Ouyang, Wanli and Wang, Xiaogang},
  booktitle={CVPR},
  year={2016}
}](https://github.com/Cysu/dgd_person_reid/blob/master/data/format_cuhk03.py)

**Comment by Yukun-Huang** [comment]
Hi, the split protocol files are provided in `data_splits/` from [Google Drive](https://drive.google.com/drive/folders/1anHkFyEJaQWRsbkmVFjZX9y71zzb7rCs?usp=sharing).
